In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,mean_absolute_error
from sklearn.model_selection import train_test_split,cross_val_score

In [2]:
df=pd.read_csv("Advertising.csv")

In [3]:
df.head()

Unnamed: 0     TV  Radio  Newspaper  Sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [4]:
df.drop("Unnamed: 0",axis=1,inplace=True)

In [5]:
df

TV  Radio  Newspaper  Sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3    9.3
3    151.5   41.3       58.5   18.5
4    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1    9.7
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4

[200 rows x 4 columns]

In [6]:
X=df.drop(["Sales"],axis=1)
y=df[["Sales"]]

In [7]:
X

TV  Radio  Newspaper
0    230.1   37.8       69.2
1     44.5   39.3       45.1
2     17.2   45.9       69.3
3    151.5   41.3       58.5
4    180.8   10.8       58.4
..     ...    ...        ...
195   38.2    3.7       13.8
196   94.2    4.9        8.1
197  177.0    9.3        6.4
198  283.6   42.0       66.2
199  232.1    8.6        8.7

[200 rows x 3 columns]

In [8]:
y

Sales
0     22.1
1     10.4
2      9.3
3     18.5
4     12.9
..     ...
195    7.6
196    9.7
197   12.8
198   25.5
199   13.4

[200 rows x 1 columns]

In [9]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1)

In [10]:
X_train.head()

TV  Radio  Newspaper
108   13.1    0.4       25.6
107   90.4    0.3       23.2
189   18.7   12.1       23.4
14   204.1   32.9       46.0
56     7.3   28.1       41.4

In [11]:
y_train.head()

Sales
108    5.3
107    8.7
189    6.7
14    19.0
56     5.5

In [12]:
X_test.head()

TV  Radio  Newspaper
58   210.8   49.6       37.7
40   202.5   22.3       31.6
34    95.7    1.4        7.4
102  280.2   10.1       21.4
184  253.8   21.3       30.0

In [13]:
y_test.head()

Sales
58    23.8
40    16.6
34     9.5
102   14.8
184   17.6

In [14]:
reg_model=LinearRegression()
reg_model.fit(X_train,y_train)

LinearRegression()

In [15]:
reg_model.coef_    ### ilk katsayı TV, ikinci Radio, üçüncü ise Newspaper için bulundu.

array([[0.0468431 , 0.17854434, 0.00258619]])

In [16]:
reg_model.intercept_   ### sabit terim olarak bulundu.

array([2.90794702])

## GENEL DENKLEM
### sales=2.907 + 0.0468431 x TV + 0.17854434 x radio + 0.00258619 x newspaper

In [17]:
TV=100
radio=25
newspaper=25
# kendimiz elle hesaplarsak
# sales=2.90794702 + 100x0.0468431 + 25x0.17854434 + 25x0.00258619       sonuçta: Sales=12,1205... çıkar


In [18]:
s=2.907 + 0.0468431 * TV + 0.17854434 * radio + 0.00258619 * newspaper

In [19]:
s

12.11957325

# regresyon ile kontrol etme 

In [20]:
x=[[100,25,25]]
y_prediction=reg_model.predict(x)

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [21]:
y_prediction

array([[12.12052059]])

In [22]:
# MSE (Mean_Squared_Error)
y_pred=reg_model.predict(X_test)
mean_squared_error(y_test,y_pred)     # hataların uzaklıklarının kareleri toplamı

1.9918855518287901

In [23]:
# RMSE (Root_Mean_Squared_Error)
np.sqrt(mean_squared_error(y_test,y_pred))

1.4113417558581587

In [24]:
# MAE (Mean_Absolute_Error)
y_pred=reg_model.predict(X_test)
mean_absolute_error(y_test,y_pred) # hataların mutlak değer uzaklıklarının toplamı

1.0402154012924716

In [25]:
# R_square 
reg_model.score(X_test,y_test) 
# modelin açıklama gücü...... asıl bakılacak değer budur. 
# Bağımlı değişkendeki değişimin yüzdesel olarak kaçta kaçının bağımsız değişkenler tarafından açıklandoığını gösterir.

0.8927605914615384